spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 172.16.11.228:9092
          zk-nodes: 172.16.11.228:2181
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 1