#京东下单错误码对应终端的提示
errorCodeMessage:
  jdOrderCodeNote:
    3001: 系统出问题了，请稍后再试。
    3002: 订单提交过于频繁，请稍后再试。
    3005: 抱歉，没有找到该商品
    3008: 抱歉，商品库存不足
    3009: 抱歉，订单中有此区域不可购买的商品
    3010: 抱歉，请单独购买订单内商品。
    3016: 系统出问题了，请稍后再试。
    3017: 抱歉，余额不足，支付失败
    3018: 系统出问题了，请退出后重新进入。
    3019: 系统出问题了，请退出后重新进入。
    3051: 系统出问题了，请退出后重新进入。
    3052: 系统出问题了，请退出后重新进入。
    3053: 系统出问题了，请退出后重新进入。
    3054: 系统出问题了，请退出后重新进入。
    3055: 系统出问题了，请退出后重新进入。
    3056: 系统出问题了，请退出后重新进入。
    3057: 系统出问题了，请退出后重新进入。
    3058: 系统出问题了，请退出后重新进入。
    3101: 系统繁忙，请重新下单
    3103: 请勿重复下单。
    3201: 取消订单失败，请重新取消订单
    3203: 请勿重复取消订单
    3204: 该订单已经生产，无法取消
    3401: 抱歉，未找到对应订单。
    3402: 抱歉，未找到配送信息
    3403: 抱歉，余额不足，支付失败
    5001: 服务异常，请稍后重试
    5002: 未知错误
    2004: 请删除下架商品
    0010: 商品已下架